### ISSUE TITLE
HU04 - Consultar la información detallada de un artista

### ISSUE THREAD

**Issue by omoralessu** [cccortesc1/MISW4203_Grupo21_Vinilos#7]
Como usuario visitante quiero ver el detalle de un artista para ampliar la información sobre él.

 **Tareas**

- [x] Revisar posibles ajustes sobre el diseño.
- [x] Consumir el servicio correspondiente de la API.
- [x] Montar el componente donde vamos consumir el servicio (visualización).
- [x] Pruebas funcionales.
- [x] Pruebas unitarias.
- [x] Documentar.

**Comment by cccortesc1** [comment]
Completado
